# Generated by Django 5.0.4 on 2024-05-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='notes',
            field=models.TextField(default='Add Note Here...'),
        ),
    ]
