# Generated by Django 5.0.4 on 2024-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_webpage_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
